#!/bin/bash

# vim-plug
test -f ~/.vimrc && cp ~/.vimrc ~/.vimrc_backup
test ! -f ~/.vim/autoload/plug.vim && curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

#vimrc
cp .vimrc ~/.vimrc

#install plugins
vim -c 'PlugInstall' -c 'qa!'
